/**
 * Course Structure Generation Prompt Builder
 *
 * Constructs prompts for AI-powered course structure generation.
 * Handles course configuration, arc structure, research instructions, and output formatting.
 */

import type { CourseStructureGenerationRequest } from '$lib/schemas/apiValidator';
import { buildResearchInstructions, buildSupportingDocuments, buildSection } from '$lib/utils/prompt/shared-components';

/**
 * Build the course structure generation prompt from input data
 *
 * @param data - Course structure request with configuration and arc details
 * @returns Formatted prompt string for Claude
 */
export function buildCourseStructurePrompt(data: CourseStructureGenerationRequest): string {
	// Build conditional sections
	const supportingDocs = data.supportingDocuments
		? '\n\n' + buildSupportingDocuments(data.supportingDocuments)
		: '';

	const researchInstructions = data.enableResearch
 	? '\n' + buildSection('ResearchInstructions', buildResearchInstructions(true), false)
 	: '';

 	let arcStructureSection = '';
 	if (data.arcs && data.arcs.length > 0) {
  		arcStructureSection = `\n<ArcStructure>\nThe course is organized into ${data.arcs.length} thematic arcs:\n\n`;
  		data.arcs.forEach(arc => {
   			arcStructureSection += `Arc ${arc.order}: "${arc.title}" (${arc.durationWeeks} weeks)\n`;
   			arcStructureSection += `Theme: ${arc.theme}\n`;
   			arcStructureSection += `Description: ${arc.description}\n`;

   			if (arc.modules && arc.modules.length > 0) {
    				arcStructureSection += `Modules within this arc:\n`;
    				arc.modules.forEach(module => {
     					arcStructureSection += `  - Module ${module.order}: "${module.title}" (${module.durationWeeks} weeks)\n`;
              if (module.description) {
                arcStructureSection += `    ${module.description}\n`
              };
    				});
   			} else {
    				arcStructureSection += `(Modules to be auto-generated by AI)\n`;
   			}

   			arcStructureSection += `\n`;
  		});
  		arcStructureSection += `</ArcStructure>`;
 	}

 	return `<Task>
    You are designing a course structure for a ${data.structure} ${data.totalWeeks}-week course organized into thematic ARCS.

    <CourseDetails>
    <Title>${data.title}</Title>
    <Description>${data.description}</Description>
    <Duration>${data.totalWeeks} weeks, ${data.daysPerWeek} day(s) per week</Duration>
    <CohortSize>${data.cohortSize} learners</CohortSize>
    <Structure>${data.structure}</Structure>
    <LearnerExperience>
      - Related field experience: ${data.learnerExperience.prereq}
      - Course focus experience: ${data.learnerExperience.focus}
    </LearnerExperience>
    </CourseDetails>
    ${supportingDocs}
    ${arcStructureSection}
    ${researchInstructions}

    <Instructions>
    The course is organized using ARCS - thematic learning phases that group related modules.

    1. Generate a cohesive course narrative that explains the overall learning journey across all arcs
    ${data.enableResearch ? '   - Use web search to validate that the course approach reflects current industry practice' : ''}

    2. For EACH ARC:
      - Generate an arcThemeNarrative explaining the thematic focus and what learners will explore
      - Generate an arcProgressionNarrative explaining how modules within THIS arc build on each other
      - If modules are provided, enhance them with detailed objectives and topics
      - If modules are NOT provided, intelligently break down the arc into 2-4 modules based on arc duration and theme
    ${data.enableResearch ? '   - Use web search to ensure topics and technologies are current' : ''}

    3. For EACH MODULE (whether provided or generated):
      - Refined title (improve if needed, keep if good)
      - Rich description of what learners will focus on
      - 3-5 specific, measurable learning objectives
      - 4-6 key topics that will be covered
    ${data.enableResearch ? '   - Use web search to validate learning objectives match current industry needs' : ''}

    4. Ensure:
      - Modules within each arc build on each other progressively
      - Arcs are thematically independent but temporally sequenced
      - Content complexity matches learners' experience levels
      - The ${data.structure} teaching structure is reflected in recommendations
    ${data.enableResearch ? '   - All content reflects current best practices discovered through research' : ''}

    Format your response as a JSON object with this structure:
    {
      "courseNarrative": "2-3 paragraph narrative describing the overall course journey and how arcs connect thematically",
      "arcs": [
        {
          "order": 1,
          "title": "Arc title",
          "description": "Arc description",
          "theme": "Thematic focus",
          "arcThemeNarrative": "2-3 sentences explaining this arc's thematic focus",
          "arcProgressionNarrative": "2-3 sentences explaining how modules in this arc connect",
          "suggestedDurationWeeks": number,
          "modules": [
            {
              "order": 1,
              "title": "Module title",
              "description": "2-3 sentence description",
              "suggestedDurationWeeks": number,
              "learningObjectives": ["objective 1", "objective 2", ...],
              "keyTopics": ["topic 1", "topic 2", ...]
            }
          ]
        }
      ],
      "progressionNarrative": "1-2 paragraphs explaining how arcs connect across the course (note: arcs are thematically independent but sequenced)"
    }

    Think carefully about creating logical thematic arcs with meaningful internal progression that take learners from their current level to meaningful competence.
    </Instructions>
  </Task>`;
}
